// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Mon Mar 27 15:38:11 2023

ToneDetector_Module ToneDetector_Module_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.enable(enable_sig) ,	// input  enable_sig
	.dataIn(dataIn_sig) ,	// input [15:0] dataIn_sig
	.done(done_sig) ,	// output  done_sig
	.Tone(Tone_sig) 	// output [15:0] Tone_sig
);

